/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vn.edu.iuh.fit.miniprojectattt.container;

import vn.edu.iuh.fit.miniprojectattt.conponents.AES;

import javax.swing.*;
import java.math.BigInteger;

/**
 * @author Dell
 */
public class FrameASE extends javax.swing.JFrame {

    private AES aes = new AES();

    /**
     * Creates new form JFrameASE
     */
    public FrameASE() {
        initComponents();
    }

    private boolean checkKey(String key) {
        if (key.length() != 16) {
            JOptionPane.showMessageDialog(this, "Khóa phải có 16 ký tự");
            return false;
        }
        return true;
    }

    private void btnMaHoaActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_btnMaHoaActionPerformed
        String input = areaInput.getText();
        if (input.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập chuỗi cần mã hóa");
            return;
        }
        String message = areaInput.getText();
        if (!checkKey(textKey.getText())) {
            return;
        }
        String encrypted = aes.encrypt(message, textKey.getText());
        areResult.setText(encrypted);
    }//GEN-LAST:event_btnMaHoaActionPerformed

    private void btnGiaiMaActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_btnGiaiMaActionPerformed
        String input = areaInput.getText();
        if (input.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập chuỗi cần giải mã");
            return;
        }
        String encrypted = areaInput.getText();
        if (!checkKey(textKey.getText())) {
            return;
        }
        String decrypted = aes.decrypt(encrypted, textKey.getText());
        areResult.setText(decrypted);
    }//GEN-LAST:event_btnGiaiMaActionPerformed

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lableHeaderText = new javax.swing.JLabel();
        btnMaHoa = new javax.swing.JButton();
        btnGiaiMa = new javax.swing.JButton();
        panelString = new javax.swing.JPanel();
        lableString = new javax.swing.JLabel();
        scrollPanelString = new javax.swing.JScrollPane();
        areaInput = new javax.swing.JTextArea();
        panelKey = new javax.swing.JPanel();
        lableKey = new javax.swing.JLabel();
        textKey = new javax.swing.JTextField();
        panelResult = new javax.swing.JPanel();
        lableResult = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areResult = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lableHeaderText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lableHeaderText.setForeground(new java.awt.Color(0, 0, 153));
        lableHeaderText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lableHeaderText.setText("Thuật toán ASE");

        btnMaHoa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMaHoa.setText("Mã hóa");
        btnMaHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btnMaHoaActionPerformed(evt);
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
            }
        });

        btnGiaiMa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGiaiMa.setText("Giải mã");
        btnGiaiMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btnGiaiMaActionPerformed(evt);
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
            }
        });

        panelString.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lableString.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lableString.setText("Chuỗi");

        areaInput.setColumns(20);
        areaInput.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        areaInput.setRows(5);
        scrollPanelString.setViewportView(areaInput);

        javax.swing.GroupLayout panelStringLayout = new javax.swing.GroupLayout(panelString);
        panelString.setLayout(panelStringLayout);
        panelStringLayout.setHorizontalGroup(
                panelStringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelStringLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lableString, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollPanelString, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelStringLayout.setVerticalGroup(
                panelStringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelStringLayout.createSequentialGroup()
                                .addGroup(panelStringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelStringLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(scrollPanelString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelStringLayout.createSequentialGroup()
                                                .addGap(43, 43, 43)
                                                .addComponent(lableString, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelKey.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lableKey.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lableKey.setText("Khóa");

        textKey.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        javax.swing.GroupLayout panelKeyLayout = new javax.swing.GroupLayout(panelKey);
        panelKey.setLayout(panelKeyLayout);
        panelKeyLayout.setHorizontalGroup(
                panelKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelKeyLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lableKey, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textKey)
                                .addContainerGap())
        );
        panelKeyLayout.setVerticalGroup(
                panelKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelKeyLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(textKey, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lableKey, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelResult.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lableResult.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lableResult.setText("Kết quả:");

        areResult.setColumns(20);
        areResult.setRows(5);
        jScrollPane1.setViewportView(areResult);

        javax.swing.GroupLayout panelResultLayout = new javax.swing.GroupLayout(panelResult);
        panelResult.setLayout(panelResultLayout);
        panelResultLayout.setHorizontalGroup(
                panelResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelResultLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lableResult, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1)
                                .addContainerGap())
        );
        panelResultLayout.setVerticalGroup(
                panelResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelResultLayout.createSequentialGroup()
                                .addContainerGap(34, Short.MAX_VALUE)
                                .addComponent(lableResult, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))
                        .addGroup(panelResultLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(panelKey, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(panelResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(panelString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(203, 203, 203)
                                                                .addComponent(btnMaHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(111, 111, 111)
                                                                .addComponent(btnGiaiMa, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addGap(293, 293, 293)
                                .addComponent(lableHeaderText, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lableHeaderText, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(panelKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnMaHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnGiaiMa, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addComponent(panelResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areResult;
    private javax.swing.JTextArea areaInput;
    private javax.swing.JButton btnGiaiMa;
    private javax.swing.JButton btnMaHoa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lableHeaderText;
    private javax.swing.JLabel lableKey;
    private javax.swing.JLabel lableResult;
    private javax.swing.JLabel lableString;
    private javax.swing.JPanel panelKey;
    private javax.swing.JPanel panelResult;
    private javax.swing.JPanel panelString;
    private javax.swing.JScrollPane scrollPanelString;
    private javax.swing.JTextField textKey;
    // End of variables declaration//GEN-END:variables
}
