/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vn.edu.iuh.fit.miniprojectattt.container;

/**
 * @author Dell
 */
public class FrameHome extends javax.swing.JFrame {

    /**
     * Creates new form JFrameASE
     */
    public FrameHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lableHeaderText = new javax.swing.JLabel();
        btnGiaiMa = new javax.swing.JButton();
        btnGiaiMa1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lableHeaderText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lableHeaderText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lableHeaderText.setText("Mã hóa và giải mã thông tin");

        btnGiaiMa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGiaiMa.setText("RSA");
        btnGiaiMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiaiMaActionPerformed(evt);
            }
        });

        btnGiaiMa1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGiaiMa1.setText("ASE");
        btnGiaiMa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiaiMa1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(lableHeaderText, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(btnGiaiMa, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addComponent(btnGiaiMa1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lableHeaderText, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGiaiMa, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGiaiMa1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGiaiMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiaiMaActionPerformed
        callFrameRSA();
    }//GEN-LAST:event_btnGiaiMaActionPerformed

    private void btnGiaiMa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiaiMa1ActionPerformed
        callFrameASE();
    }//GEN-LAST:event_btnGiaiMa1ActionPerformed

    private void callFrameRSA() {
        FrameRSA frThemKH = new FrameRSA();
        frThemKH.setDefaultCloseOperation(HIDE_ON_CLOSE);
        frThemKH.setResizable(false);
        frThemKH.setVisible(true);
    }

    private void callFrameASE() {
        FrameASE frThemKH = new FrameASE();
        frThemKH.setDefaultCloseOperation(HIDE_ON_CLOSE);
        frThemKH.setResizable(false);
        frThemKH.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGiaiMa;
    private javax.swing.JButton btnGiaiMa1;
    private javax.swing.JLabel lableHeaderText;
    // End of variables declaration//GEN-END:variables
}
